#!/bin/bash
#/* Copyright (C) 2007-2012 Maxim Sokolsky, 2:5020/828.777.
#   This file is part of fidoip. It is free software and it is covered
#   by the GNU general public license. See the file LICENSE for details. */

# list echos database view

USERNAME=`whoami` ; T1="root"
if [ "$T1" = "$USERNAME" ]; then 
echo  'Please do not run this script as root' ; exit
fi

cat /usr/local/etc/fido/config | grep "Area "  > /tmp/echo.list.tmp
cat /tmp/echo.list.tmp | sed "s| -a .*||g"  | sed "s| -b .*||g" | sed "/LocalArea/d" | sed "/DupeArea/d" | sed "/NetmailArea/d" | sed "/BadArea/d"| sort >  /tmp/echo.info.tmp
ECHOINFO=`cat /tmp/echo.info.tmp`

NUMBER=`cat /tmp/echo.info.tmp | wc -l`

if [ $NUMBER = "0" ];then
echo "No echos in /usr/local/etc/fido/config"
exit
fi

echo "$NUMBER echo found in /usr/local/etc/fido/config"
echo  "=================================================="
echo "Here is echo informaion regarging"
echo "configuration file /usr/local/etc/fido/config:"
echo "Type:   Echo name:    Location:"
i=1
NUMBER=$(($NUMBER+1))
while [ "$i" -ne "$NUMBER" ]
do
echo "`sed -n ""$i"p" /tmp/echo.info.tmp`"
i=$(($i+1))
done

