#!/bin/bash
#/* Copyright (C) 2007-2012 Maxim Sokolsky, 2:5020/828.777.
#   This file is part of fidoip. It is free software and it is covered
#   by the GNU general public license. See the file LICENSE for details. */

# List additional links in /usr/local/etc/fido/link.lst

USERNAME=`whoami` ; T1="root"
if [ "$T1" = "$USERNAME" ]; then 
echo  'Please do not run this script as root' ; exit
fi

echo "--------------------------------------------------------------------"
echo ""
echo "This script list links of fidoip's FIDONet node."
echo ""
echo "--------------------------------------------------------------------"
echo ""

rm -f /tmp/link.list.tmp
rm -f /tmp/link.info.tmp

echo "==================================================="
echo "Here is MAIN link (default UPLINK)"
echo "in configuration file /usr/local/etc/fido/uplink.lst:"
echo "==================================================="
cat /usr/local/etc/fido/uplink.lst | grep "FIRST-AND-MAIN-LINK"| sed "s|####.*||g"
echo "==================================================="
echo "Here is MAIN link (default UPLINK)"
echo "connection information in /usr/local/etc/binkd.cfg:"
echo "==================================================="
cat /usr/local/etc/binkd.cfg |  grep "Main UPLINK"| sed "s|####.*||g"
echo "==================================================="
echo "All requests from AreaFix and FileFix from points "
echo "will send to this link by default if you do define"
echo "additional direct links using addlink command."
echo

sleep 2

echo

cat /usr/local/etc/fido/link.lst | grep "Link "  | sed "s|Link ||" | sed "s|\#\#\#\#||g" | sed "s/Do not edit.*//g" | sed "s|               ||" | sed "s|          ||" | sed "s|       ||" | sed "s|     ||" | sed "s|     ||" | sed "s|   ||" > /tmp/link.list.tmp
cat /tmp/link.list.tmp  >  /tmp/link.info.tmp

NUMBER=`cat /tmp/link.info.tmp | wc -l`

if [ $NUMBER = "0" ];then
echo "No additional links added to /usr/local/etc/fido/link.lst yet"
else

echo "==========================================================="
echo "Here is additional links informaion in configuration"
echo "file /usr/local/etc/fido/link.lst:"
echo "==========================================================="
echo "Link Name:   Link address:   DNS-name:      password:  "
echo ""
cat /tmp/link.info.tmp | more
echo ""
echo "==========================================================="
fi

rm -f /tmp/link.list.tmp
rm -f /tmp/link.info.tmp

